/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as AppOrgIndexRouteImport } from './routes/_app/org/index'
import { Route as AppPropertyPropertyIdRouteRouteImport } from './routes/_app/property/$propertyId/route'
import { Route as AppOrgOrgIdRouteRouteImport } from './routes/_app/org/$orgId/route'
import { Route as AppPropertyPropertyIdIndexRouteImport } from './routes/_app/property/$propertyId/index'
import { Route as AppOrgOrgIdIndexRouteImport } from './routes/_app/org/$orgId/index'
import { Route as AppPropertyPropertyIdSettingsRouteImport } from './routes/_app/property/$propertyId/settings'
import { Route as AppPropertyPropertyIdCalendarRouteImport } from './routes/_app/property/$propertyId/calendar'
import { Route as AppPropertyPropertyIdGuestsIndexRouteImport } from './routes/_app/property/$propertyId/guests/index'
import { Route as AppPropertyPropertyIdBookingsIndexRouteImport } from './routes/_app/property/$propertyId/bookings/index'
import { Route as AppPropertyPropertyIdGuestsGuestIdRouteImport } from './routes/_app/property/$propertyId/guests/$guestId'
import { Route as AppPropertyPropertyIdBookingsBookingIdRouteImport } from './routes/_app/property/$propertyId/bookings/$bookingId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOrgIndexRoute = AppOrgIndexRouteImport.update({
  id: '/org/',
  path: '/org/',
  getParentRoute: () => AppRoute,
} as any)
const AppPropertyPropertyIdRouteRoute =
  AppPropertyPropertyIdRouteRouteImport.update({
    id: '/property/$propertyId',
    path: '/property/$propertyId',
    getParentRoute: () => AppRoute,
  } as any)
const AppOrgOrgIdRouteRoute = AppOrgOrgIdRouteRouteImport.update({
  id: '/org/$orgId',
  path: '/org/$orgId',
  getParentRoute: () => AppRoute,
} as any)
const AppPropertyPropertyIdIndexRoute =
  AppPropertyPropertyIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppPropertyPropertyIdRouteRoute,
  } as any)
const AppOrgOrgIdIndexRoute = AppOrgOrgIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrgOrgIdRouteRoute,
} as any)
const AppPropertyPropertyIdSettingsRoute =
  AppPropertyPropertyIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppPropertyPropertyIdRouteRoute,
  } as any)
const AppPropertyPropertyIdCalendarRoute =
  AppPropertyPropertyIdCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AppPropertyPropertyIdRouteRoute,
  } as any)
const AppPropertyPropertyIdGuestsIndexRoute =
  AppPropertyPropertyIdGuestsIndexRouteImport.update({
    id: '/guests/',
    path: '/guests/',
    getParentRoute: () => AppPropertyPropertyIdRouteRoute,
  } as any)
const AppPropertyPropertyIdBookingsIndexRoute =
  AppPropertyPropertyIdBookingsIndexRouteImport.update({
    id: '/bookings/',
    path: '/bookings/',
    getParentRoute: () => AppPropertyPropertyIdRouteRoute,
  } as any)
const AppPropertyPropertyIdGuestsGuestIdRoute =
  AppPropertyPropertyIdGuestsGuestIdRouteImport.update({
    id: '/guests/$guestId',
    path: '/guests/$guestId',
    getParentRoute: () => AppPropertyPropertyIdRouteRoute,
  } as any)
const AppPropertyPropertyIdBookingsBookingIdRoute =
  AppPropertyPropertyIdBookingsBookingIdRouteImport.update({
    id: '/bookings/$bookingId',
    path: '/bookings/$bookingId',
    getParentRoute: () => AppPropertyPropertyIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/p/$slug': typeof PSlugRoute
  '/org/$orgId': typeof AppOrgOrgIdRouteRouteWithChildren
  '/property/$propertyId': typeof AppPropertyPropertyIdRouteRouteWithChildren
  '/org/': typeof AppOrgIndexRoute
  '/property/$propertyId/calendar': typeof AppPropertyPropertyIdCalendarRoute
  '/property/$propertyId/settings': typeof AppPropertyPropertyIdSettingsRoute
  '/org/$orgId/': typeof AppOrgOrgIdIndexRoute
  '/property/$propertyId/': typeof AppPropertyPropertyIdIndexRoute
  '/property/$propertyId/bookings/$bookingId': typeof AppPropertyPropertyIdBookingsBookingIdRoute
  '/property/$propertyId/guests/$guestId': typeof AppPropertyPropertyIdGuestsGuestIdRoute
  '/property/$propertyId/bookings/': typeof AppPropertyPropertyIdBookingsIndexRoute
  '/property/$propertyId/guests/': typeof AppPropertyPropertyIdGuestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/p/$slug': typeof PSlugRoute
  '/org': typeof AppOrgIndexRoute
  '/property/$propertyId/calendar': typeof AppPropertyPropertyIdCalendarRoute
  '/property/$propertyId/settings': typeof AppPropertyPropertyIdSettingsRoute
  '/org/$orgId': typeof AppOrgOrgIdIndexRoute
  '/property/$propertyId': typeof AppPropertyPropertyIdIndexRoute
  '/property/$propertyId/bookings/$bookingId': typeof AppPropertyPropertyIdBookingsBookingIdRoute
  '/property/$propertyId/guests/$guestId': typeof AppPropertyPropertyIdGuestsGuestIdRoute
  '/property/$propertyId/bookings': typeof AppPropertyPropertyIdBookingsIndexRoute
  '/property/$propertyId/guests': typeof AppPropertyPropertyIdGuestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/p/$slug': typeof PSlugRoute
  '/_app/org/$orgId': typeof AppOrgOrgIdRouteRouteWithChildren
  '/_app/property/$propertyId': typeof AppPropertyPropertyIdRouteRouteWithChildren
  '/_app/org/': typeof AppOrgIndexRoute
  '/_app/property/$propertyId/calendar': typeof AppPropertyPropertyIdCalendarRoute
  '/_app/property/$propertyId/settings': typeof AppPropertyPropertyIdSettingsRoute
  '/_app/org/$orgId/': typeof AppOrgOrgIdIndexRoute
  '/_app/property/$propertyId/': typeof AppPropertyPropertyIdIndexRoute
  '/_app/property/$propertyId/bookings/$bookingId': typeof AppPropertyPropertyIdBookingsBookingIdRoute
  '/_app/property/$propertyId/guests/$guestId': typeof AppPropertyPropertyIdGuestsGuestIdRoute
  '/_app/property/$propertyId/bookings/': typeof AppPropertyPropertyIdBookingsIndexRoute
  '/_app/property/$propertyId/guests/': typeof AppPropertyPropertyIdGuestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/p/$slug'
    | '/org/$orgId'
    | '/property/$propertyId'
    | '/org/'
    | '/property/$propertyId/calendar'
    | '/property/$propertyId/settings'
    | '/org/$orgId/'
    | '/property/$propertyId/'
    | '/property/$propertyId/bookings/$bookingId'
    | '/property/$propertyId/guests/$guestId'
    | '/property/$propertyId/bookings/'
    | '/property/$propertyId/guests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/p/$slug'
    | '/org'
    | '/property/$propertyId/calendar'
    | '/property/$propertyId/settings'
    | '/org/$orgId'
    | '/property/$propertyId'
    | '/property/$propertyId/bookings/$bookingId'
    | '/property/$propertyId/guests/$guestId'
    | '/property/$propertyId/bookings'
    | '/property/$propertyId/guests'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/p/$slug'
    | '/_app/org/$orgId'
    | '/_app/property/$propertyId'
    | '/_app/org/'
    | '/_app/property/$propertyId/calendar'
    | '/_app/property/$propertyId/settings'
    | '/_app/org/$orgId/'
    | '/_app/property/$propertyId/'
    | '/_app/property/$propertyId/bookings/$bookingId'
    | '/_app/property/$propertyId/guests/$guestId'
    | '/_app/property/$propertyId/bookings/'
    | '/_app/property/$propertyId/guests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
  PSlugRoute: typeof PSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/org/': {
      id: '/_app/org/'
      path: '/org'
      fullPath: '/org/'
      preLoaderRoute: typeof AppOrgIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/property/$propertyId': {
      id: '/_app/property/$propertyId'
      path: '/property/$propertyId'
      fullPath: '/property/$propertyId'
      preLoaderRoute: typeof AppPropertyPropertyIdRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/org/$orgId': {
      id: '/_app/org/$orgId'
      path: '/org/$orgId'
      fullPath: '/org/$orgId'
      preLoaderRoute: typeof AppOrgOrgIdRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/property/$propertyId/': {
      id: '/_app/property/$propertyId/'
      path: '/'
      fullPath: '/property/$propertyId/'
      preLoaderRoute: typeof AppPropertyPropertyIdIndexRouteImport
      parentRoute: typeof AppPropertyPropertyIdRouteRoute
    }
    '/_app/org/$orgId/': {
      id: '/_app/org/$orgId/'
      path: '/'
      fullPath: '/org/$orgId/'
      preLoaderRoute: typeof AppOrgOrgIdIndexRouteImport
      parentRoute: typeof AppOrgOrgIdRouteRoute
    }
    '/_app/property/$propertyId/settings': {
      id: '/_app/property/$propertyId/settings'
      path: '/settings'
      fullPath: '/property/$propertyId/settings'
      preLoaderRoute: typeof AppPropertyPropertyIdSettingsRouteImport
      parentRoute: typeof AppPropertyPropertyIdRouteRoute
    }
    '/_app/property/$propertyId/calendar': {
      id: '/_app/property/$propertyId/calendar'
      path: '/calendar'
      fullPath: '/property/$propertyId/calendar'
      preLoaderRoute: typeof AppPropertyPropertyIdCalendarRouteImport
      parentRoute: typeof AppPropertyPropertyIdRouteRoute
    }
    '/_app/property/$propertyId/guests/': {
      id: '/_app/property/$propertyId/guests/'
      path: '/guests'
      fullPath: '/property/$propertyId/guests/'
      preLoaderRoute: typeof AppPropertyPropertyIdGuestsIndexRouteImport
      parentRoute: typeof AppPropertyPropertyIdRouteRoute
    }
    '/_app/property/$propertyId/bookings/': {
      id: '/_app/property/$propertyId/bookings/'
      path: '/bookings'
      fullPath: '/property/$propertyId/bookings/'
      preLoaderRoute: typeof AppPropertyPropertyIdBookingsIndexRouteImport
      parentRoute: typeof AppPropertyPropertyIdRouteRoute
    }
    '/_app/property/$propertyId/guests/$guestId': {
      id: '/_app/property/$propertyId/guests/$guestId'
      path: '/guests/$guestId'
      fullPath: '/property/$propertyId/guests/$guestId'
      preLoaderRoute: typeof AppPropertyPropertyIdGuestsGuestIdRouteImport
      parentRoute: typeof AppPropertyPropertyIdRouteRoute
    }
    '/_app/property/$propertyId/bookings/$bookingId': {
      id: '/_app/property/$propertyId/bookings/$bookingId'
      path: '/bookings/$bookingId'
      fullPath: '/property/$propertyId/bookings/$bookingId'
      preLoaderRoute: typeof AppPropertyPropertyIdBookingsBookingIdRouteImport
      parentRoute: typeof AppPropertyPropertyIdRouteRoute
    }
  }
}

interface AppOrgOrgIdRouteRouteChildren {
  AppOrgOrgIdIndexRoute: typeof AppOrgOrgIdIndexRoute
}

const AppOrgOrgIdRouteRouteChildren: AppOrgOrgIdRouteRouteChildren = {
  AppOrgOrgIdIndexRoute: AppOrgOrgIdIndexRoute,
}

const AppOrgOrgIdRouteRouteWithChildren =
  AppOrgOrgIdRouteRoute._addFileChildren(AppOrgOrgIdRouteRouteChildren)

interface AppPropertyPropertyIdRouteRouteChildren {
  AppPropertyPropertyIdCalendarRoute: typeof AppPropertyPropertyIdCalendarRoute
  AppPropertyPropertyIdSettingsRoute: typeof AppPropertyPropertyIdSettingsRoute
  AppPropertyPropertyIdIndexRoute: typeof AppPropertyPropertyIdIndexRoute
  AppPropertyPropertyIdBookingsBookingIdRoute: typeof AppPropertyPropertyIdBookingsBookingIdRoute
  AppPropertyPropertyIdGuestsGuestIdRoute: typeof AppPropertyPropertyIdGuestsGuestIdRoute
  AppPropertyPropertyIdBookingsIndexRoute: typeof AppPropertyPropertyIdBookingsIndexRoute
  AppPropertyPropertyIdGuestsIndexRoute: typeof AppPropertyPropertyIdGuestsIndexRoute
}

const AppPropertyPropertyIdRouteRouteChildren: AppPropertyPropertyIdRouteRouteChildren =
  {
    AppPropertyPropertyIdCalendarRoute: AppPropertyPropertyIdCalendarRoute,
    AppPropertyPropertyIdSettingsRoute: AppPropertyPropertyIdSettingsRoute,
    AppPropertyPropertyIdIndexRoute: AppPropertyPropertyIdIndexRoute,
    AppPropertyPropertyIdBookingsBookingIdRoute:
      AppPropertyPropertyIdBookingsBookingIdRoute,
    AppPropertyPropertyIdGuestsGuestIdRoute:
      AppPropertyPropertyIdGuestsGuestIdRoute,
    AppPropertyPropertyIdBookingsIndexRoute:
      AppPropertyPropertyIdBookingsIndexRoute,
    AppPropertyPropertyIdGuestsIndexRoute:
      AppPropertyPropertyIdGuestsIndexRoute,
  }

const AppPropertyPropertyIdRouteRouteWithChildren =
  AppPropertyPropertyIdRouteRoute._addFileChildren(
    AppPropertyPropertyIdRouteRouteChildren,
  )

interface AppRouteChildren {
  AppOrgOrgIdRouteRoute: typeof AppOrgOrgIdRouteRouteWithChildren
  AppPropertyPropertyIdRouteRoute: typeof AppPropertyPropertyIdRouteRouteWithChildren
  AppOrgIndexRoute: typeof AppOrgIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppOrgOrgIdRouteRoute: AppOrgOrgIdRouteRouteWithChildren,
  AppPropertyPropertyIdRouteRoute: AppPropertyPropertyIdRouteRouteWithChildren,
  AppOrgIndexRoute: AppOrgIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
  PSlugRoute: PSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
