/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as AppAppIndexRouteImport } from './routes/_app/app/index'
import { Route as AppAppCalendarRouteImport } from './routes/_app/app/calendar'
import { Route as AppAppPropertiesIndexRouteImport } from './routes/_app/app/properties/index'
import { Route as AppAppGuestsIndexRouteImport } from './routes/_app/app/guests/index'
import { Route as AppAppBookingsIndexRouteImport } from './routes/_app/app/bookings/index'
import { Route as AppAppPropertiesPropertyIdRouteImport } from './routes/_app/app/properties/$propertyId'
import { Route as AppAppGuestsGuestIdRouteImport } from './routes/_app/app/guests/$guestId'
import { Route as AppAppBookingsBookingIdRouteImport } from './routes/_app/app/bookings/$bookingId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppIndexRoute = AppAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AppRoute,
} as any)
const AppAppCalendarRoute = AppAppCalendarRouteImport.update({
  id: '/app/calendar',
  path: '/app/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppAppPropertiesIndexRoute = AppAppPropertiesIndexRouteImport.update({
  id: '/app/properties/',
  path: '/app/properties/',
  getParentRoute: () => AppRoute,
} as any)
const AppAppGuestsIndexRoute = AppAppGuestsIndexRouteImport.update({
  id: '/app/guests/',
  path: '/app/guests/',
  getParentRoute: () => AppRoute,
} as any)
const AppAppBookingsIndexRoute = AppAppBookingsIndexRouteImport.update({
  id: '/app/bookings/',
  path: '/app/bookings/',
  getParentRoute: () => AppRoute,
} as any)
const AppAppPropertiesPropertyIdRoute =
  AppAppPropertiesPropertyIdRouteImport.update({
    id: '/app/properties/$propertyId',
    path: '/app/properties/$propertyId',
    getParentRoute: () => AppRoute,
  } as any)
const AppAppGuestsGuestIdRoute = AppAppGuestsGuestIdRouteImport.update({
  id: '/app/guests/$guestId',
  path: '/app/guests/$guestId',
  getParentRoute: () => AppRoute,
} as any)
const AppAppBookingsBookingIdRoute = AppAppBookingsBookingIdRouteImport.update({
  id: '/app/bookings/$bookingId',
  path: '/app/bookings/$bookingId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/p/$slug': typeof PSlugRoute
  '/app/calendar': typeof AppAppCalendarRoute
  '/app/': typeof AppAppIndexRoute
  '/app/bookings/$bookingId': typeof AppAppBookingsBookingIdRoute
  '/app/guests/$guestId': typeof AppAppGuestsGuestIdRoute
  '/app/properties/$propertyId': typeof AppAppPropertiesPropertyIdRoute
  '/app/bookings/': typeof AppAppBookingsIndexRoute
  '/app/guests/': typeof AppAppGuestsIndexRoute
  '/app/properties/': typeof AppAppPropertiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/p/$slug': typeof PSlugRoute
  '/app/calendar': typeof AppAppCalendarRoute
  '/app': typeof AppAppIndexRoute
  '/app/bookings/$bookingId': typeof AppAppBookingsBookingIdRoute
  '/app/guests/$guestId': typeof AppAppGuestsGuestIdRoute
  '/app/properties/$propertyId': typeof AppAppPropertiesPropertyIdRoute
  '/app/bookings': typeof AppAppBookingsIndexRoute
  '/app/guests': typeof AppAppGuestsIndexRoute
  '/app/properties': typeof AppAppPropertiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/p/$slug': typeof PSlugRoute
  '/_app/app/calendar': typeof AppAppCalendarRoute
  '/_app/app/': typeof AppAppIndexRoute
  '/_app/app/bookings/$bookingId': typeof AppAppBookingsBookingIdRoute
  '/_app/app/guests/$guestId': typeof AppAppGuestsGuestIdRoute
  '/_app/app/properties/$propertyId': typeof AppAppPropertiesPropertyIdRoute
  '/_app/app/bookings/': typeof AppAppBookingsIndexRoute
  '/_app/app/guests/': typeof AppAppGuestsIndexRoute
  '/_app/app/properties/': typeof AppAppPropertiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/p/$slug'
    | '/app/calendar'
    | '/app/'
    | '/app/bookings/$bookingId'
    | '/app/guests/$guestId'
    | '/app/properties/$propertyId'
    | '/app/bookings/'
    | '/app/guests/'
    | '/app/properties/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/p/$slug'
    | '/app/calendar'
    | '/app'
    | '/app/bookings/$bookingId'
    | '/app/guests/$guestId'
    | '/app/properties/$propertyId'
    | '/app/bookings'
    | '/app/guests'
    | '/app/properties'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/p/$slug'
    | '/_app/app/calendar'
    | '/_app/app/'
    | '/_app/app/bookings/$bookingId'
    | '/_app/app/guests/$guestId'
    | '/_app/app/properties/$propertyId'
    | '/_app/app/bookings/'
    | '/_app/app/guests/'
    | '/_app/app/properties/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
  PSlugRoute: typeof PSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/app/': {
      id: '/_app/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppAppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/calendar': {
      id: '/_app/app/calendar'
      path: '/app/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppAppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/properties/': {
      id: '/_app/app/properties/'
      path: '/app/properties'
      fullPath: '/app/properties/'
      preLoaderRoute: typeof AppAppPropertiesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/guests/': {
      id: '/_app/app/guests/'
      path: '/app/guests'
      fullPath: '/app/guests/'
      preLoaderRoute: typeof AppAppGuestsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/bookings/': {
      id: '/_app/app/bookings/'
      path: '/app/bookings'
      fullPath: '/app/bookings/'
      preLoaderRoute: typeof AppAppBookingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/properties/$propertyId': {
      id: '/_app/app/properties/$propertyId'
      path: '/app/properties/$propertyId'
      fullPath: '/app/properties/$propertyId'
      preLoaderRoute: typeof AppAppPropertiesPropertyIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/guests/$guestId': {
      id: '/_app/app/guests/$guestId'
      path: '/app/guests/$guestId'
      fullPath: '/app/guests/$guestId'
      preLoaderRoute: typeof AppAppGuestsGuestIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/bookings/$bookingId': {
      id: '/_app/app/bookings/$bookingId'
      path: '/app/bookings/$bookingId'
      fullPath: '/app/bookings/$bookingId'
      preLoaderRoute: typeof AppAppBookingsBookingIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAppCalendarRoute: typeof AppAppCalendarRoute
  AppAppIndexRoute: typeof AppAppIndexRoute
  AppAppBookingsBookingIdRoute: typeof AppAppBookingsBookingIdRoute
  AppAppGuestsGuestIdRoute: typeof AppAppGuestsGuestIdRoute
  AppAppPropertiesPropertyIdRoute: typeof AppAppPropertiesPropertyIdRoute
  AppAppBookingsIndexRoute: typeof AppAppBookingsIndexRoute
  AppAppGuestsIndexRoute: typeof AppAppGuestsIndexRoute
  AppAppPropertiesIndexRoute: typeof AppAppPropertiesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAppCalendarRoute: AppAppCalendarRoute,
  AppAppIndexRoute: AppAppIndexRoute,
  AppAppBookingsBookingIdRoute: AppAppBookingsBookingIdRoute,
  AppAppGuestsGuestIdRoute: AppAppGuestsGuestIdRoute,
  AppAppPropertiesPropertyIdRoute: AppAppPropertiesPropertyIdRoute,
  AppAppBookingsIndexRoute: AppAppBookingsIndexRoute,
  AppAppGuestsIndexRoute: AppAppGuestsIndexRoute,
  AppAppPropertiesIndexRoute: AppAppPropertiesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
  PSlugRoute: PSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
